-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.todos
(
    todo_id SERIAL NOT NULL,
    description text COLLATE pg_catalog."default",
    completed boolean DEFAULT false,
    user_id integer,
    CONSTRAINT todos_pkey PRIMARY KEY (todo_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id SERIAL NOT NULL,
    username VARCHAR(255) COLLATE pg_catalog."default" NOT NULL UNIQUE,
    email VARCHAR(255) COLLATE pg_catalog."default" UNIQUE,
    password text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public.todos
    ADD CONSTRAINT fk_user_todo FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;